# Write the Simplest Test in JavaScript.

Supongamos que hemos codificado una función en la que se supone que dentro de la misma se van a sumar los valores de los dos parámetros que recibe pero debido a un error en la implementación nos equivocamos tecleando y hacemos que realice la resta de los dos parámetros.

```js
const sum = (a, b) => a - b
```

Evidentemete estamos ante un bug que es relativamente sencillo de encontrar y también de corregir sin más que cambiar el operador resta `-` por el operador suma `+`. Sin embargo lo que nos puede interesar es disponer de un mecanismo que impida que este error vuelva a aparecer otra vez.

La mayoría de las herramientas que tenemos para poder realizar los test dentro de nuestras aplicaciones pasan por lanzar un error en el momento en el que ocurre una condición que provoca que uno o más test no pasen. Así, basándonos en esta idea vamos a realizar el código que nos permita comprobar que nuestra función `sum` estará funcionando como esperamos.

```js
const sum = (a, b) => a - b

const result = sum(3, 7)
const expected = 10
if (result !== expected) {
  throw new Error(`${ result } is not equal to ${ expected }.`)
}
```

Como se puede ver simplemente lo que estamos haciendo es invocar a la función con dos valores concretos de los cuáles conocemos cuál es el resultado que prentendemos obtener y en el caso de que el resultado obtenido no sea el que esperábamos simplemente lo que haremos será lanzar un error.

Si guardamos nuestro trabajo en el fichero `simple.js` y desde una terminal del sistema invocamos a NodeJS para que lo ejecute podemos ver cómo se nos muestra un error:

```console
$ node simple.js
  [....]
  Error: -4 is not equal to 10
  [...]
```

Si ahora corregimos nuestra función para que pase de utilizar el operador `-` por el operador `+`:

```js
const sum = (a, b) => a + b

const result = sum(3, 7)
const expected = 10
if (result !== expected) {
  throw new Error(`${ result } is not equal to ${ expected }.`)
}
```

Y volvemos a ejecutar nuestro código no obtenemos ningún resultado por la consola ya que no se produce el error ya que el resultado que hemos obtenido al invocar a la función `sum` es exactamente el que se esperábamos:

```console
$ node simple.js
$
```

Vamos ahora a crear un nuevo test pero en este caso para una nueva función `subtract` que se encargará de realizar la resta de los dos valores que recibe como parámetro siguiendo la misma filosofía para su creación:

```js
const sum = (a, b) => a + b
const subtract = (a, b) => a - b

let result = sum(3, 7)
let expected = 10
if (result !== expected) {
  throw new Error(`${ result } is not equal to ${ expected }.`)
}

result = subtract(7, 3)
expected = 4
if (result !== expected) {
  throw new Error(`${ result } is not equal to ${ expected }.`)
}
```

Si volvemos a guardar nuestro trabajo y a ejecutar los test podemos ver que no se lanza un error por lo que podemos concluir que el código de las funciones está pasando lo test que hemos definido.

```console
$ node simple.js
$
```

<br />

----
<div>
  <div style="float: left">
    <a href="">
      < Intro to Fundamentals of Testing in JavaScript
    </a>
  </div>
  <div style="float: right">
    <a href="">
      Built a JavaScript Assertion Library >
    </a>
  </div>
</div>